// Login Check Types
export const LOGIN_CHECK_SUCCESS = 'LOGIN_CHECK_SUCCESS';
export const LOGIN_CHECK_LOADING = 'LOGIN_CHECK_LOADING';
export const LOGIN_CHECK_ERROR = 'LOGIN_CHECK_ERROR';

// Login Action Types
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_LOADING = 'LOGIN_ACTION_LOADING';
export const LOGIN_ACTION_ERROR = 'LOGIN_ACTION_ERROR';

// Logout Action Types
export const LOGOUT_ACTION_SUCCESS = 'LOGOUT_ACTION_SUCCESS';
export const LOGOUT_ACTION_LOADING = 'LOGOUT_ACTION_LOADING';
export const LOGOUT_ACTION_ERROR = 'LOGOUT_ACTION_ERROR';

// Get Data Types
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
